name: Pull request upstream into remote
on:
  push:
    branches:
      - clean
jobs:
  pullRequestCreation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          branch: pull-requester
          delete-branch: true          